<?php

namespace Database\Seeders;

use App\Models\Attendant;
use App\Models\Doctor;
use App\Models\Nurse;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                'id' => 1,
                'name' => 'Ichigo Kurosaki',
                'email' => 'ichigo@bleach.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-1111',
                'cpf' => '111.111.111-11',
                'sex' => 'male',
                'birth' => '2000-07-15',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/f/f6/Ichigo_Kurosaki.png',
                'place_of_birth' => 'Karakura',
                'city' => 'Karakura Town',
                'neighborhood' => 'Centro',
                'street' => 'Rua Kurosaki',
                'block' => 'A1',
                'apartment' => '101',
                'role' => 'patient',
                'age' => 24,
            ],
            [
                'id' => 2,
                'name' => 'Rukia Kuchiki',
                'email' => 'teste@nurse.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-2222',
                'cpf' => '222.222.222-22',
                'sex' => 'female',
                'birth' => '2001-01-14',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/1/1d/Rukia_Kuchiki.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Leste',
                'street' => 'Rua Kuchiki',
                'block' => 'B2',
                'apartment' => '202',
                'role' => 'nurse',
                'age' => 23,
            ],
            [
                'id' => 3,
                'name' => 'Orihime Inoue',
                'email' => 'teste@attendant.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-3333',
                'cpf' => '333.333.333-33',
                'sex' => 'female',
                'birth' => '2002-09-03',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/9/9d/Orihime_Inoue.png',
                'place_of_birth' => 'Karakura',
                'city' => 'Karakura Town',
                'neighborhood' => 'Norte',
                'street' => 'Rua Inoue',
                'block' => 'C3',
                'apartment' => '303',
                'role' => 'attendant',
                'age' => 22,
            ],
            [
                'id' => 4,
                'name' => 'Uryū Ishida',
                'email' => 'teste@doc.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-4444',
                'cpf' => '444.444.444-44',
                'sex' => 'male',
                'birth' => '2000-11-06',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/8/88/Ury%C5%AB_Ishida.png',
                'place_of_birth' => 'Karakura',
                'city' => 'Karakura Town',
                'neighborhood' => 'Oeste',
                'street' => 'Rua Ishida',
                'block' => 'D4',
                'apartment' => '404',
                'role' => 'doctor',
                'age' => 24,
            ],
            [
                'id' => 5,
                'name' => 'Renji Abarai',
                'email' => 'teste@doc2.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-5555',
                'cpf' => '555.555.555-55',
                'sex' => 'male',
                'birth' => '1999-08-31',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/7/7c/Renji_Abarai.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Sul',
                'street' => 'Rua Abarai',
                'block' => 'E5',
                'apartment' => '505',
                'role' => 'doctor',
                'age' => 25,
            ],
            [
                'id' => 6,
                'name' => 'Byakuya Kuchiki',
                'email' => 'teste@adm.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-6666',
                'cpf' => '666.666.666-66',
                'sex' => 'male',
                'birth' => '1998-01-31',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/8/83/Byakuya_Kuchiki.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Centro',
                'street' => 'Rua Kuchiki Clan',
                'block' => 'F6',
                'apartment' => '606',
                'role' => 'admin',
                'age' => 26,
            ],
            [
                'id' => 7,
                'name' => 'Tōshirō Hitsugaya',
                'email' => 'teste@nurse2.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-7777',
                'cpf' => '777.777.777-77',
                'sex' => 'male',
                'birth' => '2003-12-20',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/e/e3/T%C5%8Dshir%C5%8D_Hitsugaya.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Leste',
                'street' => 'Rua Hitsugaya',
                'block' => 'G7',
                'apartment' => '707',
                'role' => 'nurse',
                'age' => 21,
            ],
            [
                'id' => 8,
                'name' => 'Kisuke Urahara',
                'email' => 'teste@doc3.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-8888',
                'cpf' => '888.888.888-88',
                'sex' => 'male',
                'birth' => '1988-12-31',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/5/5a/Kisuke_Urahara.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Comércio',
                'street' => 'Loja Urahara',
                'block' => 'H8',
                'apartment' => '808',
                'role' => 'doctor',
                'age' => 36,
            ],
            [
                'id' => 9,
                'name' => 'Yoruichi Shihōin',
                'email' => 'yoruichi@bleach.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-9999',
                'cpf' => '999.999.999-99',
                'sex' => 'female',
                'birth' => '1995-02-11',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/a/a5/Yoruichi_Shih%C5%8Din.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Centro',
                'street' => 'Rua Shihōin',
                'block' => 'I9',
                'apartment' => '909',
                'role' => 'admin',
                'age' => 29,
            ],
            [
                'id' => 10,
                'name' => 'Kenpachi Zaraki',
                'email' => 'kenpachi@bleach.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone' => '(11) 99999-0000',
                'cpf' => '000.000.000-00',
                'sex' => 'male',
                'birth' => '1990-05-10',
                'photo' => 'https://static.wikia.nocookie.net/bleach/images/d/d5/Kenpachi_Zaraki.png',
                'place_of_birth' => 'Soul Society',
                'city' => 'Karakura Town',
                'neighborhood' => 'Distrito 11',
                'street' => 'Rua Zaraki',
                'block' => 'J10',
                'apartment' => '1010',
                'role' => 'doctor',
                'age' => 34,
            ],
        ]);
    }
}